[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Vitor Novo", email = "vitor@novocs.com.br"}]
dynamic = ["version", "description"]
